/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7bhCmy1u8Qb
 */
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import SignOutButton from "../components/SignOutButton"

export default function portal() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex h-16 justify-between items-center px-6 bg-gray-900 text-white">
        <h1 className="text-2xl font-bold">My Portal</h1>
        <SignOutButton />
      </header>
      <main className="flex-1 bg-gray-100 py-8">
        <section className="container mx-auto px-6 mb-8">
          <h2 className="text-3xl font-bold mb-4">Featured Courses</h2>
          <div className="grid grid-cols-3 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Course 1</CardTitle>
              </CardHeader>
              <CardContent>
                <BookIcon className="h-6 w-6 mb-2" />
                <p>Description for Course 1</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Course 2</CardTitle>
              </CardHeader>
              <CardContent>
                <BookIcon className="h-6 w-6 mb-2" />
                <p>Description for Course 2</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Course 3</CardTitle>
              </CardHeader>
              <CardContent>
                <BookIcon className="h-6 w-6 mb-2" />
                <p>Description for Course 3</p>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="container mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4">Popular Services</h2>
          <div className="grid grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Service 1</CardTitle>
              </CardHeader>
              <CardContent>
                <CogIcon className="h-6 w-6 mb-2" />
                <p>Description for Service 1</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Service 2</CardTitle>
              </CardHeader>
              <CardContent>
                <CogIcon className="h-6 w-6 mb-2" />
                <p>Description for Service 2</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Service 3</CardTitle>
              </CardHeader>
              <CardContent>
                <CogIcon className="h-6 w-6 mb-2" />
                <p>Description for Service 3</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Service 4</CardTitle>
              </CardHeader>
              <CardContent>
                <CogIcon className="h-6 w-6 mb-2" />
                <p>Description for Service 4</p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
    </div>
  )
}


function BookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function CogIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  )
}
